/*
WM8731
------
1. Audio Codec(Coder/Decoder)
2. Configured by I2C protocal
3. Data trasmitted by I2S protocal

I2C: 100kHz
WM8731: 12MHz

Clocks
=======
1. clk: raw FPGA clock, 50MHz
2. Reference clock for WM8731: <= 100kHz, generated by PLL from clk
- time the I2C bit-banging
- not sent to WM8731, only for internal use
3. SCL: I2C clock <= 400kHz, derived from reference clock, sent to WM8731
- just use counter for 25kHz
- only for I2C
- Derived from reference clock

------ WM8731 handles the following signals ------
4. BCLK: I2S bit clock, depends on sample rate
5. LRCLK: I2S left-right clock, depends on sample rate, derived from BCLK
*/

// create SCL
// create SDA
// create FSM to send I2C settings

module I2cInitializer (
    input i_rst_n,
    input i_clk, // 100kHz, reference clock
    input i_start,
    output o_finished,
    output o_sclk,
    output o_sdat,
    output o_oen
);
    localparam logic [23:0] configBits [0:9] = '{
        24'b0011_0100_000_0000_0_1001_0111,
        24'b0011_0100_000_0001_0_1001_0111,
        24'b0011_0100_000_0010_0_0111_1001,
        24'b0011_0100_000_0011_0_0111_1001,
        24'b0011_0100_000_0100_0_0001_0101,

        24'b0011_0100_000_0101_0_0000_0000,
        24'b0011_0100_000_0110_0_0000_0000,
        24'b0011_0100_000_0111_0_0100_0010,
        24'b0011_0100_000_1000_0_0001_1001,
        24'b0011_0100_000_1001_0_0000_0001
    };

    typedef enum logic [1:0] {
        IDLE,
        START,
        DATA,
        STOP
    } state_t;

    state_t state_r, state_w;


    logic SCL_r, SCL_w, SDA_r, SDA_w, oen_r, oen_w, fin_r, fin_w;
    logic [2:0] scl_cnt_r, scl_cnt_w;
    logic [4:0] data_bit_idx_r, data_bit_idx_w;
    logic [4:0] data_word_idx_r, data_word_idx_w; // index for configBits
    assign o_sclk = SCL_r;
    assign o_sdat = SDA_r;
    assign o_oen = oen_r;
    assign o_finished = fin_r;

    // ========== FSM ==========
    // ---- Current State Logic ----
    always_ff @(posedge i_clk or negedge i_rst_n) begin
        if (!i_rst_n) begin
            state_r <= IDLE;
            scl_cnt_r <= 0;
            data_bit_idx_r <= 0;
            data_word_idx_r <= 0;
            SCL_r <= 1;
            SDA_r <= 1;
            oen_r <= 0;
            fin_r <= 0;
        end else begin
            state_r <= state_w;
            scl_cnt_r <= scl_cnt_w;
            data_bit_idx_r <= data_bit_idx_w;
            data_word_idx_r <= data_word_idx_w;
            SCL_r <= SCL_w;
            SDA_r <= SDA_w;
            oen_r <= oen_w;
            fin_r <= fin_w;
        end
    end
    // ---- Next State Logic ----
    always_comb begin
        // default values
        state_w = state_r;
        scl_cnt_w = scl_cnt_r;
        data_bit_idx_w = data_bit_idx_r;
        data_word_idx_w = data_word_idx_r;
        oen_w = oen_r;
        SDA_w = SDA_r;
        SCL_w = SCL_r;
        fin_w = fin_r;

        case (state_r)
            IDLE: begin
                fin_w = 0;
                if (i_start) begin
                    state_w = START;
                end
            end
            START: begin
                SDA_w = 0;
                SCL_w = 1;
                oen_w = 0; // drive SDA
                scl_cnt_w = 0;
                data_bit_idx_w = 23; // start from MSB
                data_word_idx_w = 0; // start from first config word
                state_w = DATA;
            end
            DATA: begin
                // update SCL
                SCL_w = (scl_cnt_r < 2) ? 0 : 1; // SCL low for 2 cycles, then high for 2 cycles
                if (scl_cnt_r == 3) begin
                    scl_cnt_w = 0;
                end else begin
                    scl_cnt_w = scl_cnt_r + 1;
                end

                // update SDA when SCL is low
                if (SCL_r == 0) begin
                    SDA_w = configBits[data_word_idx_r][data_bit_idx_r];
                end

                // move to next bit after SCL goes high
                if (scl_cnt_r == 3) begin
                    data_bit_idx_w = data_bit_idx_r - 1;
                    if ((data_bit_idx_r == 16 || data_bit_idx_r == 8 || data_bit_idx_r == 0) && oen_r == 0) begin
                        oen_w = 1; // release SDA for ACK bit
                        data_bit_idx_w = data_bit_idx_r;
                    end else begin
                        oen_w = 0; // drive SDA for data bits
                    end
                    // move to next word after finishing current word
                    if (data_bit_idx_r == 0 && oen_r == 1) begin
                        data_word_idx_w = data_word_idx_r + 1;
                        data_bit_idx_w = 23; // start from MSB of next word
                    end
                    // after sending all words, move to STOP state
                    if (data_word_idx_r == 10 && data_bit_idx_r == 0 && oen_r == 1) begin
                        state_w = STOP;
                    end
                end
            end

            STOP: begin
                SDA_w = 0;
                SCL_w = 1;
                oen_w = 0; // drive SDA
                // generate stop condition
                if (scl_cnt_r == 3) begin
                    SDA_w = 1; // release SDA while SCL is high
                    oen_w = 0; // release SDA
                    fin_w = 1;
                    state_w = IDLE;
                end else begin
                    scl_cnt_w = scl_cnt_r + 1;
                end



            end



        endcase
    end






endmodule